version: "3"
services:
  appfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge
