version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3012:3012"
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - todo-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  todo-data:
